### ISSUE TITLE
Investigate integration with Open-CTI

### ISSUE THREAD

**Issue by rhohimer** [oasis-open/tac-ontology#36]
OpenCTI is becoming a popular choice of front end. We should investigate the possibility of using a TAC knowledgegraph to support the backend model for OpenCTI.

**Comment by rhohimer** [comment]
I spent a few minutes reading the OpenCTI website. I thought I was just going to refresh my memory on their status, however, I was surprised at the advances that have been made.  It is significant that they are now have a GraphQL API. This merits investigation. This may allow us to communicate between the OpenCTI back-end data model and a Knowledge Graph governed by TAC ontologies and extensions to the TAC ontologies (e.g., TAL)

@TCReg I'll be looking into this more in the near future.

**Comment by TCReg** [comment]
Interesting, I'll have to check it out.  Thanks.

    On Saturday, August 19, 2023 at 12:46:41 PM MST, Ryan Hohimer ***@***.***> wrote:  
 
 


I spent a few minutes reading the OpenCTI website. I thought I was just going to refresh my memory on their status, however, I was surprised at the advances that have been made. It is significant that they are now have a GraphQL API. This merits investigation. This may allow us to communicate between the OpenCTI back-end data model and a Knowledge Graph governed by TAC ontologies and extensions to the TAC ontologies (e.g., TAL)

@TCReg I'll be looking into this more in the near future.

**Comment by rhohimer** [comment]
I have reviewed the OpenCTI platform with the intension of evaluating the possibility of creating a graph based back-end to the OpenCTI platform which uses the TAC-Ontologies.  This Issue is about building a platform that uses the TAC ontologies and not about issues with the TAC-Ontology. Hence I am closing the issue.
