### ISSUE TITLE
Mapping TAC ontology to MISP galaxies? 

### ISSUE THREAD

**Issue by adulau** [oasis-open/tac-ontology#40]
How is the integration of TAC ontology foreseen with [MISP galaxies](https://github.com/MISP/misp-galaxy)?   

There is already a documented mapping (especially on the UUID uses) for STIX 2.1 at the following location: [https://misp.github.io/misp-stix/documentation/misp_galaxies_to_stix21.html](https://misp.github.io/misp-stix/documentation/misp_galaxies_to_stix21.html)

**Comment by rhohimer** [comment]
@adulau I will bring this topic up in our Working Session tomorrow!

**Comment by rhohimer** [comment]
A potential route to map MISP galaxies to the TAC ontology would be to use the existing converter and an @context for the resulting STIX 2.1 JSON documents.

**Comment by rhohimer** [comment]
I think that having started the creation of an @context file for STIX 2.1 JSON files that an easier solution to converting STIX 2.1 JSON documents to TAC knowledge graphs is SPARQL-Anything. see: https://github.com/SPARQL-Anything/sparql.anything 

Investigating it.

**Comment by rhohimer** [comment]
I just had an epiphany. We can easily convert STIX 2.1 JSON into a TAC Knowledge Graph without converting to JSON-DL first.  We can use SPARQL-Anything to convert the STIX 2.1 JSON contents into stix:StixObject instances. Then the TAC ontology can infer the correct class type from the "type" key on each stix:StixObject

This is a huge break through...

If I'm correct in my thinking, I could be loading valid STIX 2.1 JSON documents into a TAC Knowledge Graph very soon. If I didn't have other things to do it could be as soon as the end of the weekend.

**Comment by rhohimer** [comment]
I'll continue to investigate this STIX 2.1 JSON to TAC Knowledge Graph conversion. 

@adulau can you locate a MISP Galaxy that has be converted to a valid STIX 2.1 JSON representation?
