### ISSUE TITLE
Implement the stix:GroupingContextOv in the STIX Ontology

### ISSUE THREAD

**Issue by rhohimer** [oasis-open/tac-ontology#48]
{“suspicious-activity”, “malware-analysis”, “unspecified”}

This would seem to be one of the simplest Open Vocabulary issues. It only has three terms in the vocabulary.

**Comment by rhohimer** [comment]
Tim Casey may be working on this implementation. In our working sessions he has installed GitHub, the RDF-toolkit, and Protégé, We need to figure out how to assign issues to Tim Casey.

**Comment by TCReg** [comment]
Ryan figured out the assignment and I am assigned to this issue.

**Comment by rhohimer** [comment]
I reviewed the Pull Request and merged the branch into the develop branch.
