### ISSUE TITLE
Develop standard approach to recording Action Items

### ISSUE THREAD

**Issue by TCReg** [oasis-open/tac-ontology#56]
Research best way to ensure action items are recorded and tracked, including those who may not have a GitHub account.  Get TC consensus approval on proposal.

**Comment by TCReg** [comment]
Doh! Sorry, forgot to update you on this:  There is a method within GitHub Issues that allows you to create projects, and then task lists within the projects, which could be used for action items.  Unfortunately it is rather unwieldy and fairly limited, and in any case is way more than what we need.  So I propose instead we use a spreadsheet to track simple and well-defined tasks assigned to individuals, such as contacting a resource or uploading files. These will typically have a binary status, Done/Not Done.  We'd use Issues to record, discuss, and track progress toward things like problem resolution, large projects, new features, ideas for investigation, and other involved, higher-impact items.  We'd also need to create a short document to explain the difference and their uses.  
How does that sound?

    On Friday, July 14, 2023 at 03:40:59 PM MST, Ryan Hohimer ***@***.***> wrote:  
 
 


Let me know how I can help with this. This is "sort of" why we started using the GitHub Issue Tracker.

**Comment by rhohimer** [comment]
I think you may be right about creating projects as being "too much".  However, I'd like to look into it a bit. I know that a spreadsheet is simpler, but it is not as "built in".   There are some projects that I would like to see started that might benefit from the Github project feature (e.g., ThreatScenario, Extension Mechanism).  It might work for **subcommittees** to have there own project.

**Comment by TCReg** [comment]
It does make sense to keep all the documentation together.  A very simple solution might be to create an "Action Item" tag for entering these as Issues, flagging it as a simpler task vs. an extended project.

    On Saturday, July 22, 2023 at 03:26:56 PM MST, Ryan Hohimer ***@***.***> wrote:  
 
 


I think you may be right about creating projects as being "too much". However, I'd like to look into it a bit. I know that a spreadsheet is simpler, but it is not as "built in". There are some projects that I would like to see started that might benefit from the Github project feature (e.g., ThreatScenario, Extension Mechanism). It might work for subcommittees to have there own project.

**Comment by rhohimer** [comment]
Adding an "Action Item" tag, or maybe an "Action Required" tag may help, but I still feel that actions items are not tracked well with the Issue Tracker.

**Comment by rhohimer** [comment]
Filtering by Action Item label AND assignee  may be adequate for a while.
